---
title: "R for Data Science"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x= displ, y = hwy))

#ggplot(data = <DATA>) +
 # <GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))

```


```{r}
#add color
ggplot(data = mpg) +
  geom_point(mapping = aes(x= displ, y = hwy, color = class))

```

```{r}
#add size to variable 
ggplot(data = mpg) +
  geom_point(mapping = aes(x= displ, y = hwy, size = class))
#Warning: not a good idea to use size for discrete variable
```


```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x= displ, y = hwy, alpha = class))
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x= displ, y = hwy, shape = class, alpha = class))

```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x= displ, y = hwy), color = "blue")
#adding color outside of the mapping will make the whole graph that color

```

```{r}
ggplot(data = mpg) +
  geom_point(
    mapping = aes(x= displ, y = hwy, color = "blue")
    )

```

```{r}
#adding thickness by stroke
ggplot(data = mpg) +
  geom_point(mapping = aes(x= displ, y = hwy, stroke = 2))

```

```{r}


```


```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x=displ, y= hwy))
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x= displ, y= hwy)) +
  facet_wrap(~ class, nrow = 2)
```

```{r}
glimpse(mpg)
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(drv ~ cyl)
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(. ~ cyl)
```

```{r}
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x= displ,y=hwy,  = drv))
```

```{r}

```



